# Generated by Django 4.0.4 on 2023-06-27 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("process_manager", "0008_formtype_formfield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "étape", "verbose_name_plural": "étapes"},
        ),
        migrations.AlterModelOptions(
            name="phase",
            options={"verbose_name": "phase"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "projet"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "tâche"},
        ),
    ]
