# Generated by Django 4.0.4 on 2023-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process_manager", "0009_alter_activity_options_alter_phase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="manager_role",
            field=models.CharField(
                choices=[
                    ("AC-SDCC", "Assistant coordonnateur spécialiste du dcc"),
                    ("FGB", "Formateur en gestion à la base"),
                    ("SC", "Superviseur communal"),
                    ("FT", "Facilitateur technique"),
                    ("FC", "Facilitateur communautaire"),
                ],
                default="FC",
                max_length=32,
            ),
        ),
    ]
