# Generated by Django 4.0.4 on 2023-06-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_facilitator_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="role",
            field=models.CharField(
                choices=[
                    ("AC-SDCC", "Assistant coordonnateur spécialiste du dcc"),
                    ("FGB", "Formateur en gestion à la base"),
                    ("SC", "Superviseur communal"),
                    ("FT", "Facilitateur technique"),
                    ("FC", "Facilitateur communautaire"),
                ],
                default="FC",
                max_length=32,
            ),
        ),
    ]
