# Generated by Django 4.0.4 on 2023-08-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_facilitator_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitator",
            name="code",
            field=models.CharField(max_length=32, unique=True, verbose_name="code"),
        ),
    ]
