# Generated by Django 4.0.4 on 2023-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_facilitator_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitator",
            name="fullname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
