from extended_choices import Choices

ADMINISTRATIVE_LEVEL_TYPE = Choices(
    ("DÉPARTEMENT", "département", "Département"),
    ("COMMUNE", "commune", "Commune"),
    ("ARRONDISSEMENT", "arrondissement", "Arrondissement"),
    ("VILLAGE", "village", "Village"),
)

PROJECT_STRUCTURE = {"phase": "phase", "activity": "étape", "task": "tâche"}

AGENT_ROLE = Choices(
    ("ACSDCC", "AC-SDCC", "Assistant coordonnateur spécialiste du dcc"),
    ("FGB", "FGB", "Formateur en gestion à la base"),
    ("SC", "SC", "Superviseur communal"),
    ("FT", "FT", "Facilitateur technique"),
    ("FC", "FC", "Facilitateur communautaire"),
)
AGENT_ROLE_CH = (
    ("", ""),
    ("SC", "SC"),
    ("FC", "FC"),
    ("FGB", "FGB"),
    ("FT", "FT"),
    ("AC-SDCC", "AC-SDCC"),
)
FC_COVERAGE = ["village"]
SC_FT_COVERAGE = ["arrondissement"]

# set to 1 hour
AGENT_TASKS_COMPLETION_TIMEOUT = 3600

# temp constants # to be deleted
# atacora donga
ADM1 = [
    "KAKPÉSSIA",
    "KOUSSOCOINGOU",
    "KOUMONTCHIRGOU",
    "MORWATCHOHI",
    "TCHIMBÉRI",
    "NATCHÉNTÉ",
    "KOUNADOGOU",
    "BOROYINDÉ",
    "SINAOURAROU",
    "DINGOU",
    "BAYAKOU",
    "DATORI",
    "ANGARADÉBOU DE DJOUGOU2",
    "ZONGO DE BOUKOUMBE",
    "ITCHÈLLI",
    "SONATÉ",
    "ATACORA",
    "TORICONCONÉ",
    "ADÉDÉWO",
    "KOUSSOUNOUNGOU",
    "PÉNESSOULOU",
    "DIPOLI",
    "BASSALA",
    "IGBÈRÈ",
    "KOUKOUANKPANGOU",
    "KPARSI",
    "KOUANDE",
    "GORA -PEULH",
    "KPÉLOUDÈ",
    "SEMERE 2",
    "MANOUGOU",
    "SOMPARÉROU-GAH",
    "SAPAHA",
    "TCHALINGA",
    "AKARADÈ",
    "KOUKOUANGOU-BOUKOUMBÉ",
    "KAKABOUNOU-BÉRI",
    "KPÉLITÉ",
    "IKOUNGA",
    "KOUMAAGOU",
    "IGADOUGOU",
    "TARPINGOU",
    "TÈKÈ-TÉROU",
    "OULI",
    "TIMTIM-BONGO",
    "KADIÉNI",
    "KOUPAGOU",
    "SOASSARAROU",
    "SINAOU",
    "GUILMARO",
    "BÊKET",
    "TANFÉRÉ",
    "TONRI",
    "OUKPÈTOUHOUN",
    "KAWADO",
    "DIMANSOURI",
    "MÊLAN",
    "GBAOU",
    "KOUWETAKOUANGOU",
    "TOKIBI",
    "TANGUIETA",
    "KPETISSOHOUN",
    "OUKOUNSÉRIHOUN",
    "KOUATIDABIRGOU",
    "GUIMBÉRÉROU",
    "AWANLA",
    "GOUNTIA",
    "FOO-TANCE",
    "GAH",
    "BOUÉROU",
    "NOWÊRÈRÈ",
    "MANIGRI-OKÉ SOUANGBÉ",
    "OUASSA - KIKA",
    "PÉTONI-POHO-GOROBANI",
    "MODOGUI",
    "TOBRÉ",
    "DISSAPOLI",
    "MANTCHARI",
    "TABA",
    "DITCHENDIA",
    "KPAKOU-TANKONGA",
    "KAGNIFÊLÊ",
    "KAOUTÉ",
    "ALAYOMDÈ",
    "DONGA",
    "OROUKOUARÉ",
    "WOLO",
    "TOBRE",
    "SOUBROUKOU",
    "COBLY",
    "DJOUGOU I",
    "BOUTOU",
    "PARTAGO DE ALEDJO",
    "SONAHOLOU",
    "GOGONIGA",
    "TATOUTA",
    "KOUSSOUCOINGOU",
    "PÉHUNCO I",
    "NAGAYILÉ",
    "KODOWARI",
    "KABARÉ",
    "YÉDÉKAHOUN",
    "TORA",
    "NODI",
    "AWOTOBI",
    "MADINA DE DJOUGOU1",
    "TCHALADÈ",
    "GONRI",
    "DAMOUTI",
    "TIPAOTI",
    "GAO",
    "PÉNÉLAN",
    "SINAOURAROU-GAH",
    "KOUSSAYAGOU",
    "KILIR",
    "KPATOUHOU",
    "PEHUNCO",
    "GUILMARO-BOUNKOSSOROU",
    "ZONGO DE DJOUGOU1",
    "DJOUGOU",
    "KOUTAYAGOU",
    "TIGNINTI",
    "BORIFIÉRI",
    "KOUNTORI",
    "GUILMARO-GARKOUSSON",
    "KOUARHOUN",
    "BOUDÉ",
    "PÉMOMBOU",
    "NASSOU",
    "OUASSA-MARO",
    "TCHÉTOU",
    "GNANGBA KABIA",
    "KOUKOULOUNDA",
    "PÉHUNCO II",
    "TCHAMONGA",
    "BONBORH",
    "NAMATIÉNOU",
    "TAÏFA",
    "WANNOU",
    "COTIAKOU",
    "TAMPOURÉ-POGUÉ",
    "KPAKPALARÉ",
    "MATERI",
    "ALÉDJO",
    "KPÉLI-FADA",
    "GAMBINOU",
    "KADÉGUÉ",
    "LÉMAN-MANDÈ",
    "ASSARADÈ",
    "NINGOUSSOUROU",
    "AGUÉOU-GARBA",
    "NASSOUKOU",
    "MADJATOM",
    "GOUTÉRÉ",
    "KOUTCHATAHONGOU",
    "KAMOUHOU",
    "LÉMAN-BOGOU",
    "KOUKOUATCHIENGOU",
    "KOUTATIÉGOU",
    "MAHONTIKA",
    "BORO DE GUIMARO",
    "KOUSSETIEGOU",
    "ALFA-ISSA",
    "WOKOU DE PEHUNCO",
    "SASSIROU",
    "NALOHOU",
    "KOUDAHONGOU",
    "KOUNADORGOU",
    "BOUKOUMBE",
    "OTANONGOU",
    "BOUNTA",
    "MANIGRI-IKANNI",
    "KÈDÉKOU",
    "KOUMAGOU",
    "OROUBOUSSOUKOU",
    "WARGOU",
    "N’ TCHIÉGA",
    "KASSUA-ALLAH",
    "FOUNGA",
    "TROUCARÉ-BAS",
    "SONNOUGOBÉROU",
    "DAGUIMAGNINNI",
    "N’DJAKADA",
    "SÈLROU",
    "KOTOTOUGOU",
    "PÉHONCO-TATAPOURANOU",
    "TCHAPÉTA",
    "BODI",
    "SALMANGA",
    "KPIKIRÉ KOKA",
    "HOLLI DE NODI",
    "KPÉRÉHOUN",
    "DANRI DE FOO_TANCE",
    "TIKOU",
    "DJAKPINGOU",
    "DIDOMPÊ",
    "LANDA",
    "BASSILA",
    "KANTÈ",
    "MAKA",
    "MANIGRI",
    "FOO-MAMA",
    "WAKITÈ",
    "YARI",
    "SÉRI",
    "DJOUGOU II",
    "KOUMATIÉ",
    "MARÉ OROU GAH",
    "DIKOUMINI",
    "PÉTONI-POHO- PARTAGO",
    "PENESSOULOU",
    "PARABOU",
    "FOO",
    "MANIGRI OKÉ IGBOÉLÉ",
    "NATITINGOU",
    "NAMOUTCHAGA",
    "AWO",
    "NIBADARA",
    "SINNI",
    "OUAKE",
    "NIORO- KOLINA",
    "KPÉRINKPÉ",
    "ALEDJO",
    "TAKPANTA",
    "SERHOUNGUÈ",
    "OUTANONHOUN",
    "GUILMARO-SINAKPAGOUROU",
    "KOTARI",
    "GBÉBA DE PEHUNCO",
    "SOAODOU",
    "PÉHUNCO-GAH",
    "KOUGNANGOU",
    "MATALÈ",
    "KOUTCHATA",
    "BÊKET - GAH",
    "BANA",
    "OUKPINTIHOUN",
    "OUROUFINA",
    "KOUANDATA",
    "TANCÉ",
    "SOBITÈ",
    "KOUNTCHOUGOU",
    "KOUTIE",
    "KOUTAGOU",
    "NAGNANDÉ",
    "WAKAROU",
    "CORONCORÉ",
    "PENITINGOU",
]
# borgou alibori
ADM2 = [
    "GNEL-BOUCATOU",
    "SÉKO-KPAROU",
    "GOSSODJI",
    "GNEL-DJOBO",
    "GOLOBANDA",
    "MÉLAYAKOUARA",
    "BORO",
    "SEKERE",
    "KASSA",
    "KARIMAMA",
    "WONKO DERASSI",
    "BAGARIA",
    "ADA-KPANÉ",
    "BESSASSI-BOUCA",
    "GUINROU-PEULH",
    "GAANON",
    "YARRA-KOURI",
    "GNELSANDA",
    "BODJÉCALI",
    "GNINSY-GANDO",
    "KANTORO",
    "DIGUIDIROU",
    "BELLO-TOUNGA",
    "BANIKANI",
    "TCHICANDOU",
    "YARRA-PEULH",
    "SENDÉ",
    "KOMPA",
    "MAMASSY-GOURMA",
    "KARÈL",
    "KPÉROU-GUÉRA",
    "MAFOUTA-WAASSARÈ",
    "BATAZI",
    "KPARO",
    "KOUALÉROU",
    "WOLLO-CHÂTEAU",
    "GNONKOURAKALI",
    "WARA-GAH",
    "TASSI-DJINDÉ",
    "WOROU-TOKOROU",
    "SOUNBEY-GOROU",
    "OUENOU",
    "LAKALI-KANEY",
    "ALAFIAROU-DÉRASSI",
    "KOTCHI",
    "BOÏFFO",
    "GORÉ",
    "BÈYAROU",
    "YARRA-BARIBA",
    "KOUARA-TÉDJI",
    "SÈKÈRÈ-PEULH",
    "GUÉNÉ KOUZI",
    "SOUBO-BARAWOROU",
    "GANDO-BAKA",
    "WORIA",
    "PIAMI",
    "TASSO",
    "SAMTIMBARA",
    "DÉPÔT",
    "GBÉKPANIN",
    "GBABIRÉ",
    "KORODJI",
    "WÉKÉTÈRÈ",
    "OUROUMON",
    "GBÉROUGBASSI",
    "BANIKANNI-DOUWÉROU",
    "SANDILO-GANDO",
    "BOUKOUSSÉRA",
    "PERERE",
    "ALIBORI",
    "KAALA",
    "KONTOUBAROU",
    "GUINROU",
    "SANSI",
    "MADÉCALI",
    "GNINSY",
    "SANRÉKOU",
    "NIKKI",
    "MOKOLLÉ",
    "OUÉZÉ",
    "DANGAZORI",
    "BOUNDAROU",
    "GOROUSSOUNDOUGOU",
    "GBESSARÈ",
    "BANITÈ-FÈRÈ KIRÈ",
    "BOUCA-PEULH",
    "ALBARIKA",
    "SAKANA- KPÉBA",
    "GALIEL",
    "KÉNÉ-TOUNGA",
    "WOLLO",
    "ANGARADÉBOU DE PÉONGA",
    "THIAN",
    "FO- DAROU",
    "KPÉBOURABOU",
    "SOUKAROU",
    "GARAROU",
    "TOUKOSSARI",
    "MADÉCALI-ZONGO",
    "BOGO-BOGO",
    "GOTEL",
    "GARBEY-KOARA",
    "ALAFIAROU DE OUENOU",
    "GOUROU BÉRI",
    "KOARATÉDJI",
    "SÈKÈRÈ-GANDO",
    "KOROWI",
    "TOUCARÈ",
    "KARIMAMA-BATOUMA-BÉRI",
    "BAKPÉROU",
    "GOUNIN DE PARAKOU1",
    "CHEIN-TASSO",
    "GNINSY-PEULH",
    "KAKATINNIN",
    "TÉKPAROU",
    "KADÉRA",
    "TITIROU",
    "DÉRASSI",
    "SOUMON-GAH",
    "TANAKPÉ",
    "SÈKÈRÈ-MARO",
    "GUIRI-PEULH",
    "YARRA-GANDO",
    "MADECALI",
    "BOA",
    "TASSI-TÉDJI",
    "ZAZIRA",
    "MADINA DE PRKOU1",
    "KALALE",
    "WARA-GBIDOGO",
    "BOUCA",
    "GOUSSOUAMBOU",
    "SAWARAROU",
    "DAMAGOUROU",
    "BORGOU",
    "GBASSI",
    "MAREGUINTA",
    "SÉRÉGOUROU",
    "FAKARA",
    "GUÉNÉ-ZERMÉ",
    "TCHAOUROU",
    "TOUROU-PALAIS-ROYAL",
    "TASSI-TÉDJI-BOULANGA",
    "BODJÉCALI-CHÂTEAU",
    "ASSAGNAHOUN",
    "TORIOH",
    "ISSÉNÉ",
    "GUEMA",
    "GOURE BABA",
    "GAN -GBÉROU",
    "GOGOUNOU",
    "SEGBANA",
    "GBARI",
    "BADÉKPAROU",
    "KOMPANTI",
    "GANNOURÈ-HÈRÈ",
    "BANITÈ-KOUBÉRI",
    "KARIMAMA-DENDI-KOURÉ",
    "ATIRA-KPAROU",
    "TOURA",
    "BOA-GANDO",
    "TONDI-BANDA",
    "GBÉÏ",
    "MONNON DE PARAKOU1",
    "BANIZOUMBOU",
    "FIAFOUNFOUN",
    "TOUROU-DISPENSAIRE",
    "KOUBOU",
    "WOROUMANGASSAROU",
    "KABASSIRA",
    "GOROBANI DE GNINSY",
    "MAMASSY-PEULH",
    "GOUN-GOUN",
    "KOUREL",
    "GODJÉKOARA",
    "DOUGOU",
    "TASSI-ZÉNON",
    "KPÉBIÉ DE PARAKOU1",
    "SOUROU",
    "GUIRI-GANDO",
    "GOUNGOU-BÉRI",
    "KOFOUNOU",
    "SANDILO",
    "BAKINKOURA",
    "GUENE",
    "BOUCA-GANDO",
    "OUÉNOU -NIKKI",
    "KINNOU-KPAROU",
    "KOUKOUMBOU",
    "TORO-ZOUGOU",
    "TCHATCHOU",
    "WOURO-YESSO",
    "DIGUIDIROU -PEULH",
    "PÉONGA",
    "DASSARI DE WARA",
    "GNEL-YAKAN",
    "PEONGA",
    "SINANGOUROU",
    "GOKANNA",
    "OUROUMONSI- PEULH",
    "SOMBIRIKPÉROU",
    "ILLOUA",
    "GUÉNÉ-GUIDIGO",
    "DÉMAN",
    "ALAGA",
    "GOUROU-PIBOU",
    "FOMBAWI",
    "FONDO",
    "BANGOU",
    "GNEL-KÉLÉ",
    "WARA",
    "SOUBO-GANDÉROU",
    "MATCHORÈ",
    "GNELKIRADJÉ",
    "BOUCA-WOOROU",
    "CAMP-ADAGBÈ",
    "SINAGOUROU",
    "BOSSO-CAMPS-PEULHS",
    "GANDO-GOUROU",
    "KPASSANA",
    "PARAKOU",
    "SINENDE",
    "TASSI-TÉDJI-BANIZOUNBOU",
    "LIMAFRANI",
    "DERASSI",
    "1ER  ARRONDISSEMENT",
    "BOURAOURÈ",
    "MALANVILLE",
    "KALÉ",
    "GNELTOKO",
]
ADM_LIST = ADM1 + ADM2
ADM3 = [
    "ATACORA",
    "GORGOBA",
    "SAKASSON-DOMPAGO",
    "GBÉNIKI",
    "HONGON",
    "GOUFANROU",
    "PAPATIA",
    "WÉMÈ",
    "TASSIGOUROU",
    "BIRNI-KANKOULKA",
    "SAKASSON-DITAMARI",
    "YAKABISSI",
    "CHABI COUMA",
    "BIRNI MARO",
    "CHABI – COUMA",
    "KOUBORO",
    "GANTIÉCO",
    "TAMANDÉ",
    "KOUANDE",
    "BIRNI-KPÉBIROU",
    "BIRNI",
]
USERNAMES = ["SOUNKOUA_N'dah", "OROU_KINNOU", "MAMAN_Taariq", "YANTO_Innocent"]
ADM4 = ["IGBÈRÈ", "MODOGUI"]
